name: run-notebooks
on:
<<<<<<< HEAD
=======
  schedule:
      - cron: "0 0/2 * * *"
>>>>>>> origin/main
  push: 
    branches:
      - main
    paths:
      - "notebooks/**"
  pull_request:
    branches:
      - main
    paths:
      - "notebooks/**"
<<<<<<< HEAD
  schedule:
      - cron: "0 0/2 * * *"
=======
>>>>>>> origin/main
jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        notebook: ['notebooks/train-lightgbm-local.ipynb']
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.8"
    - name: pip install
      run: pip install -r requirements.txt
<<<<<<< HEAD
    - name: check code format
      run: black --check .
    - name: check notebook format
      run: black-nb --clear-output --check .
=======
>>>>>>> origin/main
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: install azmlcli
      run: az extension add -s https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.15.0-py3-none-any.whl -y
    - name: attach to workspace
      run: az ml folder attach -w default -g azureml-examples
    - name: run notebook
      run: papermill ${{matrix.notebook}} out.ipynb -k python
